### ISSUE TITLE
Nothing showing in hosts manager

### ISSUE THREAD

**Issue by roynasser** [gbk/chrome-hosts-manager#9]
A while ago hosts manager stopped working... Any idea how I can debug/fix it?

I'm on osx yosemite with chrome.  I tried chmod on /etc/hosts, it doesnt even read the current hosts...

![image](https://cloud.githubusercontent.com/assets/1218902/8219359/e013b2b6-151f-11e5-980e-75ebf1bd99c4.png)

(tried removing and re-adding, new configs, etc)

**Comment by gbk** [comment]
I'm sorry. This extension has been blocked by chrome since a year ago for
the reason of usging npapi.
And a new extension is under development. I will email you as soon as it's
published.

**Comment by roynasser** [comment]
Great thanks... if I enable npapi support manually for now (until they disable it completely) would it work for now?

thanks! its a great extension and very useful... i miss it very much... please let me know when u have a new one

**Comment by gbk** [comment]
I'm not sure but you can try :-)

http://blog.csdn.net/isaisai/article/details/45064079
